### ISSUE TITLE
Use without streams

### ISSUE THREAD

**Issue by frank-weindel** [Freyskeyd/gulp-prompt#13]
How about functionality without using streams?

**Comment by alexnoise79** [comment]
+1

**Comment by te-gpm** [comment]
You can simply reference an empty dummy file. Should be an option though.

**Comment by baelter** [comment]
Or use inquirer directly?

**Comment by frank-weindel** [comment]
That's actually what I ended up doing and it worked perfectly.

**Comment by yuricamara** [comment]
relates to #22
