### ISSUE TITLE
Is it possible to adjust menu list height?

### ISSUE THREAD

**Issue by kokujin** [Freyskeyd/gulp-prompt#15]
I am using a prompt type "list" with several items, it starts to "scroll-wrap" after 6 items and below is a notice, "Move up and down to reveal more choices".

Is there a way to stop the wrapping or adjust the number of items displayed? Thanks

**Comment by shannonlal** [comment]
In the inquirer.js library there seems to be the option for setting the page size.  I will give this a try tomorrow to see if there is a way to get this together.

**Comment by shannonlal** [comment]
Here is the specs

https://github.com/SBoudrias/Inquirer.js#questions

**Comment by shannonlal** [comment]
I put in a quick example on how you can control the list height.  Have a look at the Readme and/or the examples directory where there is a sample gulpfile.js 

If you have any comments or questions please let me know
