### ISSUE TITLE
Feature Request: Masking passwords

### ISSUE THREAD

**Issue by chrisjlee** [Freyskeyd/gulp-prompt#21]
Thanks for this awesome gulp plugin. 

I notice that when prompting for a password the password isn't masked.

Is there a way to implement this particular feature downstream from inquirer? I see the recently fixed this in inquirer

https://github.com/SBoudrias/Inquirer.js/pull/271

If so i would love to provide a pull request and any pointers or tips to get this rectified would be helpful.

**Comment by shannonlal** [comment]
This issue is now resolved.  If you look at latest version passwords are now hidden.  If you look at the README there are two examples on Passwords and Validation.  If you have any further questions please let us know.
