### ISSUE TITLE
Can't paste in to prompts on a Windows computer

### ISSUE THREAD

**Issue by JacobDB** [Freyskeyd/gulp-prompt#25]
I love this module, but some of my Windows users are having trouble when entering values on a Windows machine. Even though Command Prompt in Windows 10 now fully supports pasting data, these inputs don't seem to register the paste commands. It's weird, because this works fine on Unix systems.

**Comment by shannonlal** [comment]
Jacob,
If you are able to put together a sample gulpfile.js then I can give it a try.  I have access to a Windows 10 computer and can try to reproduce it.  

Thanks

**Comment by JacobDB** [comment]
I've since started using Bash on Windows, and this isn't a problem there. If I get a chance, I'll see if I can reproduce it in Command Prompt.

**Comment by shannonlal** [comment]
Jacob,
I know you had mentioned before on being interested in helping out on this project.  I am currently tackling a bug about adding templating functionality into gulp-prompt (see Issue #8 ).  I think I have a potential solution but wouldn't mind having another person look at this solution to see if this works.  If this is something you are still interested please let me know and I can go over my solution with you.

Thanks

Shannon

**Comment by shannonlal** [comment]
I am going to close this off as I haven't heard any feed back and there doesn't seem to be much need for this currently
