### ISSUE TITLE
Releases and changelog

### ISSUE THREAD

**Issue by ncoden** [Freyskeyd/gulp-prompt#33]
Can you add [Github releases](https://github.com/Freyskeyd/gulp-prompt/releases) with a changelog ?

Thanks.

**Comment by shannonlal** [comment]
Tagging looks pretty easy.  The tricky part is going to be getting this automated with a pull request. Is this something you are still requiring

**Comment by shannonlal** [comment]
Thanks for creating documenting the issue.  I have created a release for the last release that was published and also added a CHANGELOG.md file.  I agree with you that this is a best practice and I will try my best to update the releases and changelog moving forward
