### ISSUE TITLE
Conditional Prompts?

### ISSUE THREAD

**Issue by tomanistor** [Freyskeyd/gulp-prompt#35]
Is it possible to chain together two prompts in the same gulp task with the 2nd prompt conditional on the value of the first prompt?

**Comment by shannonlal** [comment]
I working on something like this with run sequences but shouldn't be that hard to integrate run-sequences to chain them together

**Comment by shannonlal** [comment]
I have put in a fix for chaining prompts together.  Have a look at the readme file for this and the example files.  If you require any changes please let me know.  This is in version 0.5.0

**Comment by tomanistor** [comment]
Awesome! Thank you for adding this feature.

**Comment by shannonlal** [comment]
Let me know if there are any issues or clarifications with this feature.  I there is an issue or change you can reopen the issue and I will try to address this.
