### ISSUE TITLE
Release must use semver

### ISSUE THREAD

**Issue by Freyskeyd** [Freyskeyd/gulp-prompt#53]
Hello,

Our project must use semver for release. The v1.0 isn't semver. It should be v1.0.0

**Comment by shannonlal** [comment]
Ok.  I will fix that now

**Comment by shannonlal** [comment]
Update to this.  The package and npm naming convention are okay it just the release name in git.  I will update a fix for this and merge it in.

**Comment by shannonlal** [comment]
Fixed the correct release name.
