### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by guitarneck** [Freyskeyd/gulp-prompt#55]
Hi,

* Minor bug
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

So, it needs "use strict"; or changing all "let" by "var".

Thx.

**Comment by shannonlal** [comment]
@guitarneck thanks for pointing this out.  I will try to fix this tonight and publish and new version.

**Comment by shannonlal** [comment]
Added a fix for this issue.  let was only being used in two locations compared to var so I decided to remove it to make sure there were no backward compatibility issues
