### ISSUE TITLE
Task finishing before I could use the result of the prompt

### ISSUE THREAD

**Issue by duvalale** [Freyskeyd/gulp-prompt#57]
I have a task asking the user some translations that should be saved to a file. Except that the task finishes before the user is given a chance to answer the prompt. 

Here is a simplified version of the gulp task :

	translationPrompts = [{
 				type: 'input',
 				name: 'translation1',
 				message: 'Enter the fr translation for Name :'
 				},
                                {
 				type: 'input',
 				name: 'translation2',
 				message: 'Enter the fr translation for Debug level :'
 				}];
                
  	 gulp.task('i18n:update-locales-translations', function(done) {
 		var path = 'src/i18n/messages.fr.xlf';

 		gulp.src(path)
 		.pipe(prompt.prompt(translationPrompts, function(res) {
        	// saving res data in a file
        	},
        	parserOptions: {
        		xmlMode: true
        	}))
      .pipe(gulp.dest(config.i18n.folderPath));
      done();
 	};

 and below the result of the console :

> [16:07:10] Starting 'i18n'...
> [16:07:10] Starting 'i18n:update-locales-translations'...
> [16:07:10] Finished 'i18n:update-locales-translations' after 138 ms
> [16:07:10] Finished 'i18n' after 13 s
> ? Enter the fr translation for  Name  : rdfgd
> ? Enter the fr translation for  Debug level  : gfdg

Any idea how I could make the task wait for the prompt to be done ?
Thanks

**Comment by shannonlal** [comment]
Can you attach the full gulp file.  Also have you looked at the chain functionality.  The chain functionality allows you to chain a sequence of prompts to the user which might also work

**Comment by duvalale** [comment]
Here is the full Gulp file.

[gulpfile.js.txt](https://github.com/Freyskeyd/gulp-prompt/files/1660602/gulpfile.js.txt)


I did try the chain functionality, but couldn't make it work since the task exits before displaying the prompts.

**Comment by shannonlal** [comment]
@duvalale The file was a little large for me to debug easly.  I put together the following and wanted to see if this works for you.  If you can let me know what works and what doesn't work with this file I can help you get it up and running.

```bash
node_modules/.bin/gulp --gulpfile examples/language-test-gulpfile.js chainConfirm
```

'use strict';

var gulp = require( 'gulp' );
var prompt = require('gulp-prompt');
var index =0;

const TRANSLATION_PROMPTS = [{
        type: 'input',
        name: 'translation1',
        message: 'Enter the fr translation for Name :'
    },
    {
        type: 'input',
        name: 'translation2',
        message: 'Enter the fr translation for Debug level :'
    }
];

var chainFunction = function ( options, resp ){
    console.log( 'Here is the selection ', resp);

    if( index < TRANSLATION_PROMPTS.length ){
        options.message = TRANSLATION_PROMPTS[index].message;
        index++;
        return options;
    }else{
        return;
    }
};

/**
 * The following is a sample gulp file for chaining requests.  It 
 * will pass a chaining function to the confirm function and will 
 * allow the user to chain multiple requests together
 * variables
 * 
 */
gulp.task( 'chainConfirm',  () => {
    return gulp.src( '../package.json' )
        .pipe( prompt.confirm({
            type:'input',
            name:'env',
            message:'Enter the fr translation for Name?',
            chainFunction:chainFunction
        }, (res) => {
            console.log('Result', res);
        }) );
});

**Comment by duvalale** [comment]
I tried your code, the chain function works as is, but I can't make it work with a prompt method (the chain function is not called, by looking into your code it isn't an option of prompt), and the confirm method is not working in my case since I need the user to enter real strings and not only yes or no.
Si I would actually need to be able to chain prompt function, which is not possible for now.

**Comment by shannonlal** [comment]
@duvalale I think I know what the issue is.  I need to move the chain feature over to the prompt function; however, I will need to make sure I implement this with out breaking any code.  How fast do you need this?

If you need it quickly, I have a quick solution that will allow you to test it locally.  The issue is that the confirm function only provides a yes or no option.  I am going to show you how to modify the confirm function locally so you can test it to see if the chaining functionality works as expected.

If you open the following file:
```bash
node_modules/gulp-prompt/index.js
```

At line 90 you can add the following:

```javascript
if( typeof options.templateOptions !== 'undefined'){
        var compiled = template( options.message );
        options.message = compiled( options.templateOptions);
}

//Add the following

if( typeof options.type !== undefined && options.type !== '' ){
  //This will allow you to override the type from confirm to input
  opts.type = options.type;
}
```

If you can give this a try and let me know if this behaviour will work for you.  If this works, then I will modify the prompt function to support chaining.   Gulp-prompt gets about 50,000 downloads a month so I need to make sure when I change something that I don't break something else.

If can test it and let me know what happens.

**Comment by duvalale** [comment]
Ok, I'll try this tomorrow, and let you know if it works.

Thanks for the quick answers :)

**Comment by duvalale** [comment]
@shannonlal I tried your code and it works, but actually I noticed that I don't need to update the index.js file to make it work, setting the type option is enough (see the example below).

```javascript
var index =0;

 const TRANSLATION_PROMPTS = [{
 	type: 'input',
 	name: 'translation1',
 	message: 'Enter the fr translation for Name :'
 },
 {
 	type: 'input',
 	name: 'translation2',
 	message: 'Enter the fr translation for Debug level :'
 }
 ];

 var chainFunction = function ( options, resp ){
 	console.log( 'Here is the selection ', resp);
 	console.log(options)

 	if( index < TRANSLATION_PROMPTS.length ){
 		options.message = TRANSLATION_PROMPTS[index].message;
 		options.type = 'input'; //adding this is enough
 		index++;
 		return options;
 	}else{
 		console.log(options)
 		console.log(resp)
 		return;
 	}
 };

 gulp.task( 'chainConfirm', () => {
 	return gulp.src( 'package.json' )
 	.pipe(plugins.prompt.confirm({
 		type:'input',
 		name:'updateTranslations',
 		message:'Do you want to update translations ?',
 		chainFunction:chainFunction
 	}, (res) => {
 		console.log(res);
 	}) );
 });
```

**Comment by shannonlal** [comment]
@duvalale.  Cool I am glad that it work.  Just to confirm did this fix the issue?

**Comment by duvalale** [comment]
Yes it did, i'm closing this issue, thank you for your help !
