### ISSUE TITLE
input masking

### ISSUE THREAD

**Issue by cheesyeggdesal** [Freyskeyd/gulp-prompt#58]
is there a way to mask an input? example passwords

**Comment by shannonlal** [comment]
@cheesyeggdesal Gulp Prompt is a wrapper around inquirer.  I looked through the inquirer docs (https://www.npmjs.com/package/inquirer) and there is an input type for password.  You should be able to use the prompt function and change the input type to password.  I have put the types below.

Types:
type: (String) Type of the prompt. Defaults: input - Possible values: input, confirm, list, rawlist, expand, checkbox, password, editor

**Comment by cheesyeggdesal** [comment]
@shannonlal it worked thanks
