### ISSUE TITLE
Allow templating

### ISSUE THREAD

**Issue by contra** [Freyskeyd/gulp-prompt#8]
You should be able to use templating in the prompt message.

Use gulp-util .template for this.

**Comment by shannonlal** [comment]
I am going to start looking into this as I think this would be useful and could be helpful some of the conditional loops that other people have asked about

**Comment by shannonlal** [comment]
Sorry meant to just add comment instead of close

**Comment by shannonlal** [comment]
I am looking through this link to see how it would apply


https://github.com/gulpjs/gulp-util
https://lodash.com/docs#template

**Comment by shannonlal** [comment]
I believe I have a simple fix for this.  I have added some documentation and just waiting to publish the latest

**Comment by shannonlal** [comment]
I have put together a fix for this and it should be available in the latest release of 0.4.1
